package menu.checkout;

/**
 *
 * @author Danuarta
 */
public class mainFrame extends javax.swing.JFrame {
    public mainFrame() {
        initComponents();
        //add radio button into same group, therefore only one radio box can selected at same time in same group
        paymentMethodGroup.add(cashRadioButton);
        paymentMethodGroup.add(bniSyariahCardRadioButton);
        paymentMethodGroup.add(muamalatCardRadioButton);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // Component main form initializer configuration
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethodGroup = new javax.swing.ButtonGroup();
        menuLabel = new javax.swing.JLabel();
        JumlahLabel = new javax.swing.JLabel();
        sotoBanjarCheckBox = new javax.swing.JCheckBox();
        sateMaduraCheckBox = new javax.swing.JCheckBox();
        esJerukCheckBox = new javax.swing.JCheckBox();
        esTehCheckBox = new javax.swing.JCheckBox();
        sotoBanjarTextField = new javax.swing.JTextField();
        sateMaduraTextField = new javax.swing.JTextField();
        esJerukTextField = new javax.swing.JTextField();
        esTehTextField = new javax.swing.JTextField();
        paymenMethodPanel = new javax.swing.JPanel();
        caraBayarUpLabel = new javax.swing.JLabel();
        cashRadioButton = new javax.swing.JRadioButton();
        muamalatCardRadioButton = new javax.swing.JRadioButton();
        bniSyariahCardRadioButton = new javax.swing.JRadioButton();
        hitungButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        caraBayarDownLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warung Menu");

        menuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuLabel.setText("Menu");

        JumlahLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JumlahLabel.setText("Jumlah");

        sotoBanjarCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sotoBanjarCheckBox.setMnemonic('S');
        sotoBanjarCheckBox.setText("Soto Banjar       | Rp. 8.000");
        sotoBanjarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoBanjarCheckBoxActionPerformed(evt);
            }
        });

        sateMaduraCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sateMaduraCheckBox.setMnemonic('M');
        sateMaduraCheckBox.setText("Sate Madura     | Rp. 10.000");
        sateMaduraCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sateMaduraCheckBoxActionPerformed(evt);
            }
        });

        esJerukCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esJerukCheckBox.setMnemonic('J');
        esJerukCheckBox.setText("Es Jeruk            | Rp. 4.000");
        esJerukCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esJerukCheckBoxActionPerformed(evt);
            }
        });

        esTehCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esTehCheckBox.setMnemonic('T');
        esTehCheckBox.setText("Es Teh               | Rp. 3.500");
        esTehCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esTehCheckBoxActionPerformed(evt);
            }
        });

        sotoBanjarTextField.setEditable(false);
        sotoBanjarTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sotoBanjarTextField.setText("0");

        sateMaduraTextField.setEditable(false);
        sateMaduraTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sateMaduraTextField.setText("0");

        esJerukTextField.setEditable(false);
        esJerukTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        esJerukTextField.setText("0");

        esTehTextField.setEditable(false);
        esTehTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        esTehTextField.setText("0");

        paymenMethodPanel.setForeground(new java.awt.Color(0, 0, 0));

        caraBayarUpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        caraBayarUpLabel.setText("Cara Bayar");

        cashRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashRadioButton.setSelected(true);
        cashRadioButton.setText("Cash");

        muamalatCardRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        muamalatCardRadioButton.setText("Muamalat Card");

        bniSyariahCardRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bniSyariahCardRadioButton.setText("BNI Syariah Card");

        javax.swing.GroupLayout paymenMethodPanelLayout = new javax.swing.GroupLayout(paymenMethodPanel);
        paymenMethodPanel.setLayout(paymenMethodPanelLayout);
        paymenMethodPanelLayout.setHorizontalGroup(
            paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caraBayarUpLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashRadioButton)
                    .addComponent(muamalatCardRadioButton)
                    .addComponent(bniSyariahCardRadioButton))
                .addContainerGap())
        );
        paymenMethodPanelLayout.setVerticalGroup(
            paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caraBayarUpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muamalatCardRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bniSyariahCardRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Kosongkan");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        totalLabel.setText("Rp. 0");

        caraBayarDownLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caraBayarDownLabel.setText("Cara Bayar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caraBayarDownLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sotoBanjarCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(esJerukCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(esTehCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sateMaduraCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menuLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(JumlahLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esJerukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esTehTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sotoBanjarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sateMaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hitungButton)
                                    .addComponent(clearButton)
                                    .addComponent(totalLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paymenMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuLabel)
                    .addComponent(JumlahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sotoBanjarCheckBox)
                    .addComponent(sotoBanjarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sateMaduraCheckBox)
                    .addComponent(sateMaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esJerukCheckBox)
                    .addComponent(esJerukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esTehCheckBox)
                    .addComponent(esTehTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(hitungButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel)
                        .addGap(35, 35, 35)
                        .addComponent(clearButton)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(paymenMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(caraBayarDownLabel)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sotoBanjarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoBanjarCheckBoxActionPerformed
        // TODO add your handling code here:
        // enable textbox while checkbox is enabled, and set text starting point into 1
        // and vice versa
        if(sotoBanjarCheckBox.isSelected()){
            sotoBanjarTextField.setEditable(true);
            sotoBanjarTextField.setText("1");
        } else {
            sotoBanjarTextField.setEditable(false);
            sotoBanjarTextField.setText("0");
        }
    }//GEN-LAST:event_sotoBanjarCheckBoxActionPerformed

    private void esJerukCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esJerukCheckBoxActionPerformed
        // TODO add your handling code here:
        if(esJerukCheckBox.isSelected()){
            esJerukTextField.setEditable(true);
            esJerukTextField.setText("1");
        } else{
            esJerukTextField.setEditable(false);
            esJerukTextField.setText("0");
        }
    }//GEN-LAST:event_esJerukCheckBoxActionPerformed

    private void sateMaduraCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sateMaduraCheckBoxActionPerformed
        // TODO add your handling code here:
        if(sateMaduraCheckBox.isSelected()){
            sateMaduraTextField.setEditable(true);
            sateMaduraTextField.setText("1");
        } else{
            sateMaduraTextField.setEditable(false);
            sateMaduraTextField.setText("0");
        }
    }//GEN-LAST:event_sateMaduraCheckBoxActionPerformed

    private void esTehCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esTehCheckBoxActionPerformed
        // TODO add your handling code here:
        if(esTehCheckBox.isSelected()){
            esTehTextField.setEditable(true);
            esTehTextField.setText("1");
        } else{
            esTehTextField.setEditable(false);
            esTehTextField.setText("0");
        }
    }//GEN-LAST:event_esTehCheckBoxActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        // TODO add your handling code here:
        // convert(parsing) textField to integer, and assign it to nVariable(nSoto, nsate, etc.)
        int nSoto = Integer.parseInt(sotoBanjarTextField.getText());        
        int nSate = Integer.parseInt(sateMaduraTextField.getText());
        int nEsTeh = Integer.parseInt(esTehTextField.getText());
        int nEsJeruk = Integer.parseInt(esJerukTextField.getText());
        // Sum total
        int nTotal = (8_000*nSoto) + (10_000*nSate) + (4_000*nEsJeruk) + (3_500*nEsTeh);
        totalLabel.setText("Rp. "+nTotal);
        // Show payment method
        if (cashRadioButton.isSelected()){
            caraBayarDownLabel.setText(cashRadioButton.getActionCommand()+" payment");
        }
        if (muamalatCardRadioButton.isSelected()){
            caraBayarDownLabel.setText(muamalatCardRadioButton.getActionCommand()+" Debit payment");
        }
        if (bniSyariahCardRadioButton.isSelected()){
            caraBayarDownLabel.setText(bniSyariahCardRadioButton.getActionCommand()+ " Debit payment");
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //set up default value such as unchecked checkbox menu, textfield menu set to 0,
        // payment method default is "cash", total label default is 0, and caraBayar label to "Cara Bayar"
        sotoBanjarCheckBox.setSelected(false);
        sateMaduraCheckBox.setSelected(false);
        esJerukCheckBox.setSelected(false);
        esTehCheckBox.setSelected(false);
        sotoBanjarTextField.setText("0");
        sateMaduraTextField.setText("0");
        esJerukTextField.setText("0");
        esTehTextField.setText("0");
        sotoBanjarTextField.setEditable(false);
        sateMaduraTextField.setEditable(false);
        esJerukTextField.setEditable(false);
        esTehTextField.setEditable(false);
        cashRadioButton.setSelected(true);
        totalLabel.setText("Rp. 0");
        caraBayarDownLabel.setText("Cara Bayar");
    }//GEN-LAST:event_clearButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahLabel;
    private javax.swing.JRadioButton bniSyariahCardRadioButton;
    private javax.swing.JLabel caraBayarDownLabel;
    private javax.swing.JLabel caraBayarUpLabel;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JCheckBox esJerukCheckBox;
    private javax.swing.JTextField esJerukTextField;
    private javax.swing.JCheckBox esTehCheckBox;
    private javax.swing.JTextField esTehTextField;
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JRadioButton muamalatCardRadioButton;
    private javax.swing.JPanel paymenMethodPanel;
    private javax.swing.ButtonGroup paymentMethodGroup;
    private javax.swing.JCheckBox sateMaduraCheckBox;
    private javax.swing.JTextField sateMaduraTextField;
    private javax.swing.JCheckBox sotoBanjarCheckBox;
    private javax.swing.JTextField sotoBanjarTextField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
