package menu.checkout;

/**
 *
 * @author Danuarta
 */
public class mainFrame extends javax.swing.JFrame {
    public mainFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // Component main form initializer configuration
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethodGroup = new javax.swing.ButtonGroup();
        menuLabel = new javax.swing.JLabel();
        JumlahLabel = new javax.swing.JLabel();
        sotoBanjarCheckBox = new javax.swing.JCheckBox();
        sateMaduraCheckBox = new javax.swing.JCheckBox();
        esJerukCheckBox = new javax.swing.JCheckBox();
        esTehCheckBox = new javax.swing.JCheckBox();
        sotoBanjarTextField = new javax.swing.JTextField();
        sateMaduraTextField = new javax.swing.JTextField();
        esJerukTextField = new javax.swing.JTextField();
        esTehTextField = new javax.swing.JTextField();
        paymenMethodPanel = new javax.swing.JPanel();
        caraBayarLabel = new javax.swing.JLabel();
        cashRadioButton = new javax.swing.JRadioButton();
        muamalatCardRadioButton = new javax.swing.JRadioButton();
        bniSyariahCardRadioButton = new javax.swing.JRadioButton();
        hitungButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warung Menu");

        menuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuLabel.setText("Menu");

        JumlahLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JumlahLabel.setText("Jumlah");

        sotoBanjarCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sotoBanjarCheckBox.setMnemonic('S');
        sotoBanjarCheckBox.setText("Soto Banjar       | Rp. 8.000");
        sotoBanjarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoBanjarCheckBoxActionPerformed(evt);
            }
        });

        sateMaduraCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sateMaduraCheckBox.setMnemonic('M');
        sateMaduraCheckBox.setText("Sate Madura     | Rp. 10.000");

        esJerukCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esJerukCheckBox.setMnemonic('J');
        esJerukCheckBox.setText("Es Jeruk            | Rp. 4.000");
        esJerukCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esJerukCheckBoxActionPerformed(evt);
            }
        });

        esTehCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esTehCheckBox.setMnemonic('T');
        esTehCheckBox.setText("Es Teh               | Rp. 3.500");

        sotoBanjarTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sateMaduraTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        esJerukTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        esTehTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        paymenMethodPanel.setForeground(new java.awt.Color(0, 0, 0));

        caraBayarLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        caraBayarLabel.setText("Cara Bayar");

        cashRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashRadioButton.setSelected(true);
        cashRadioButton.setText("Cash");

        muamalatCardRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        muamalatCardRadioButton.setText("Muamalat Card");

        bniSyariahCardRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bniSyariahCardRadioButton.setText("BNI Syariah Card");

        javax.swing.GroupLayout paymenMethodPanelLayout = new javax.swing.GroupLayout(paymenMethodPanel);
        paymenMethodPanel.setLayout(paymenMethodPanelLayout);
        paymenMethodPanelLayout.setHorizontalGroup(
            paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caraBayarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashRadioButton)
                    .addComponent(muamalatCardRadioButton)
                    .addComponent(bniSyariahCardRadioButton))
                .addContainerGap())
        );
        paymenMethodPanelLayout.setVerticalGroup(
            paymenMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymenMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caraBayarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muamalatCardRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bniSyariahCardRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hitungButton.setText("Hitung");

        clearButton.setText("Kosongkan");

        totalLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        totalLabel.setText("Rp. 0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cara Bayar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sotoBanjarCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(esJerukCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(esTehCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sateMaduraCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menuLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(JumlahLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esJerukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esTehTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sotoBanjarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sateMaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hitungButton)
                                    .addComponent(clearButton)
                                    .addComponent(totalLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paymenMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuLabel)
                    .addComponent(JumlahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sotoBanjarCheckBox)
                    .addComponent(sotoBanjarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sateMaduraCheckBox)
                    .addComponent(sateMaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esJerukCheckBox)
                    .addComponent(esJerukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esTehCheckBox)
                    .addComponent(esTehTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(hitungButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel)
                        .addGap(35, 35, 35)
                        .addComponent(clearButton)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(paymenMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sotoBanjarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoBanjarCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sotoBanjarCheckBoxActionPerformed

    private void esJerukCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esJerukCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esJerukCheckBoxActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahLabel;
    private javax.swing.JRadioButton bniSyariahCardRadioButton;
    private javax.swing.JLabel caraBayarLabel;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JCheckBox esJerukCheckBox;
    private javax.swing.JTextField esJerukTextField;
    private javax.swing.JCheckBox esTehCheckBox;
    private javax.swing.JTextField esTehTextField;
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JRadioButton muamalatCardRadioButton;
    private javax.swing.JPanel paymenMethodPanel;
    private javax.swing.ButtonGroup paymentMethodGroup;
    private javax.swing.JCheckBox sateMaduraCheckBox;
    private javax.swing.JTextField sateMaduraTextField;
    private javax.swing.JCheckBox sotoBanjarCheckBox;
    private javax.swing.JTextField sotoBanjarTextField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
